---
###############################################################################
#                                                                             #
#                            WEBSITE CONFIGURATION                            #
#                                                                             #
###############################################################################


# --- base website settings ---

baseURL: https://help.traewelling.de
title: Hilfe | Träwelling
theme: inventory
languageCode: de-de
defaultContentLanguage: de
enableEmoji: true
enableGitInfo: true

# Optional: Add Google Analytics tracking support.
googleAnalytics: "" # no. just no.


# --- security settings ---

security:
  exec:
    allow: [ '^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor$', '^git$' ]



# --- markup settings ---

markup:
  asciidocExt:
    preserveTOC: true
    sectionNumbers: true
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: true
    style: murphy
    tabWidth: 4


# --- privacy settings ---

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
  twitter:
    enableDNT: true
  vimeo:
    enableDNT: true
  youtube:
    privacyEnhanced: true


# --- custom settings ---

params:
  # "Edit this page" feature: git forge content base link
  # [Example] editPrefix: https://github.com/username/repo-name/blob/main/content
  editPrefix: https://github.com/traewelling/help-pages/blob/main/content

  # Shown on all pages. When logo is empty, it will show your site title, set above.
  logo: ""

  # OpenGraph data
  description: Träwelling Help. This page is to meant to provide help for Träwelling users.
  author: Träwelling Team, and others
  # Tip: Find a royalty-free image from unsplash.com for an OpenGraph image.
  image: "images/banner.jpg"

  # customize color
  primary_color: "#c72730"
  primary_color_light: "#c63b42"
  body_color: "#f2f4f6"
  text_color: "#636363"
  text_color_dark: "#c63b42"
  text_title_color: "#ffffff"
  white_color: "#ffffff"
  light_color: "#f8f9fa"

  # font family (choose from https://fonts.google.com/)
  font_family: "Lato"
  font_offline: true

  # contact form action (works with https://formspree.io)
  contact_form_action: "#"

  # related article number limit
  article_count: 3

  # brand and identity information
  brand:
    parent_org_name: Träwelling
    parent_org_url: https://traewelling.de/
    parent_org_url_legal: https://traewelling.de/legal
  footer:
    mainSite: https://traewelling.de/
    mainSiteName: Träwelling


  # --- social platform settings ---
  # themify icon pack : https://themify.me/themify-icons

  social:
    - icon: ti-github
      name: Träwelling Help on GitHub
      link: https://github.com/traewelling/help-pages
    - icon: ti-comments-smiley
      name: "@traewelling@chaos.social on Mastodon"
      link: https://chaos.social/@traewelling


# --- taxonomy settings ---

taxonomies:
  alert: alerts
  category: categories
  downloadable: downloadBtn


# --- multilingual settings ---
Languages:
  de:
    languageName: de
    languageCode: de-de
    weight: 1
    title: "Hilfe | Träwelling"
    copyright: "Copyright &copy; 2024  [Träwelling](https://traewelling.de/)"
    params:
      banner:
        title: Womit können wir dir helfen?
        subtitle: Auf dieser Seite findest du diverse Hilfe-Artikel. Solltest du darüber hinaus Hilfe benötigen, kontaktiere uns gerne auf Mastodon oder per Mail.
        bg_image: images/banner.png
        placeholder: Du hast eine Frage? Dann durchsuche diese Webseite!

    # --- navigation menu ---
    menu:
      main:
        - name: FAQ
          weight: 10
          url: faq

  en:
    languageName: en
    languageCode: en-us
    weight: 2
    title: "Help | Träwelling"
    copyright: "Copyright &copy; 2024 [Träwelling](https://Träwelling)"
    params:
      banner:
        title: How can we help you?
        subtitle: On this page you'l find various help articles. If you have further questions, please contact us on Mastodon or via e mail.
        bg_image: images/banner.png
        placeholder: Have a question? Search the site here.

    # --- navigation menu ---
    menu:
      main:
        - name: FAQ
          weight: 10
          url: faq
